language: python


services: # => 3
      - postgresql

env: # => 4
    -DJANGO=2.2.1 DB=postregsql
    
install: # => 5
      - pip install -r requirements.txt
    
 script: # => 7
      - cd django_api
      - python manage.py test

# deploy:
#   provider: heroku
#   api_key:
#     secure: ""